baseURL = "https://binderlenz.de"
languageCode = "de-de"
title = "Binder Lenz"
themesDir = "themes"
theme = "hugo-hero-theme"

[params]
  [params.logo]
    mobile = "images/bohnen.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/binder_lenz.svg"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "Hugo Hero"

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "History"
    url = "/history/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
